export default {
  products: [
    {
      _id: "1",
      name: "Buy Shirts for Men",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 39,
      brand: "Outfitter",
      rating: 4.7,
      numReviews: 15,
      countInStock: 11,
    },
    {
      _id: "2",
      name: "Shoes for Everyone",
      category: "Shoes",
      image: "/images/product-2.jpg",
      price: 33,
      brand: "Nike",
      rating: 4.7,
      numReviews: 21,
    },
    {
      _id: "3",
      name: "Wear the best Scarf",
      category: "Scard",
      image: "/images/product-3.jpg",
      price: 29,
      brand: "Adidas",
      rating: 4.8,
      numReviews: 25,
    },
    {
      _id: "4",
      name: "best Bag",
      category: "Bag",
      image: "/images/product-4.jpg",
      price: 60,
      brand: "Armour",
      rating: 4.9,
      numReviews: 19,
      countInStock: 16,
    },
  ],
};
